module.exports = {
    //Errors
    NO_ERROR: 0,
    FETCH_ERROR: 1,
    WEATHER_ERROR: 2,
    LOCATION_ERROR: 3,
    AQI_ERROR: 4,

    //Conditions
    CLEAR: 0,
    CLOUDY: 1,
    FOG: 2,
    LIGHT_RAIN: 3,
    RAIN: 4,
    THUNDERSTORM: 5,
    SNOW: 6,
    HAIL: 7,
    WIND: 8,
    EXTREME_WIND: 9,
    TORNADO: 10,
    HURRICANE: 11,
    EXTREME_COLD: 12,
    EXTREME_HEAT: 13,
    SNOW_THUNDERSTORM: 14,

    //Weather Providers
    OPENWEATHERMAP: 0,
    //OLDYAHOO: 1,
    YAHOO: 2,
    YRNO: 3,
    FORECASTIO: 4,

    //Status bar items
    STATUS_BAR_EMPTY: 0,
    STATUS_BAR_BLUETOOTH: 1,
    STATUS_BAR_BATTERY_LEVEL: 2,
    STATUS_BAR_AQI: 3,
    STATUS_BAR_TEMP: 4,
    STATUS_BAR_CONDITION: 5,
    STATUS_BAR_AMPM: 6,
    STATUS_BAR_STEPS_SHORT: 7,
    STATUS_BAR_STEPS: 8,
    STATUS_BAR_DISTANCE: 9,
    STATUS_BAR_ACTIVE_CAL: 10,
};
